"""Project-wide settings for real-time face and hand detection."""

CAMERA_ID = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480

FACE_DETECTION_CONFIDENCE = 0.5
HAND_DETECTION_CONFIDENCE = 0.5
HAND_TRACKING_CONFIDENCE = 0.5
MAX_HANDS = 2

USE_FACE_DETECTION = True
USE_HAND_DETECTION = True

DRAW_BBOX_COLOR = (0, 255, 0)
DRAW_LANDMARK_COLOR = (255, 0, 0)

ESC_KEY = 27
